.Dd October 15, 2023
.Dt BBCP 1

.Sh NAME
.Nm bbcp
.Nd bare-bones copy a file

.Sh SYNOPSIS
.Nm
source target

.Sh DESCRIPTION
The
.Nm
utility copies the contents of the source to target.
.\" If target is a directory,
.\" .Nm
.\" will copy source into this directory.

.Sh EXAMPLES
The following examples show common usage:
.
.Bl -item -offset indent
.It
bbcp file1 file2
.\" .It
.\" bbcp file dir
.It
bbcp file1 dir/file2
.It
bbcp file1 dir/subdir/subsubdir/file2
.El
.
.Sh EXIT STATUS
.Nm
exits 0 on success, and >0 if an error occured.

.Sh SEE ALSO
.Xr bbcpm(1),
.Xr lseek(2),
.Xr read(2),
.Xr write(2)

.Sh NOTES
The code for the
.Nm
utility is, of cource, well-formatted according to the guidelines found at
.Em https://stevens.netmeister.org/631/style .
The program can be compiled using the
.Em -Wall
and
.Em -Werror
flags without any errors on warnings on a NetBSD 9.x system.

.Sh HISTORY
The
.Nm
program was first assigned as the first programming assignment for the class
CS675
.Dq Advanced Programming in the UNIX Environment
at Stevens Institute of Technology at least since around 2005.

.Sh BUGS
Well, let's see...
